spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://petshop-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://petshop-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: empolyee_route
          uri: lb://petshop-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: pet_route
          uri: lb://petshop-pet
          predicates:
            - Path=/api/pet/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: foster_route
          uri: lb://petshop-foster
          predicates:
            - Path=/api/foster/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: service_route
          uri: lb://petshop-service
          predicates:
            - Path=/api/service/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://petshop-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
## 前端项目,/api