spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: product_route
          uri: lb://petshop-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://petshop-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: empolyee_route
          uri: lb://petshop-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: pet_route
          uri: lb://petshop-pet
          predicates:
            - Path=/api/pet/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: foster_route
          uri: lb://petshop-foster
          predicates:
            - Path=/api/foster/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: service_route
          uri: lb://petshop-service
          predicates:
            - Path=/api/service/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
## 前端项目,/api