spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/petshop_fms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 43.139.126.45:8848
  application:
    name: petshop-foster
  mvc:
    static-path-pattern: /static/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#  thymeleaf:
#    cache: false
#  redis:
#    host: 192.168.16.100
#    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
server:
  port: 11000
logging:
  level:
    com.litchi.petshop: error
#feign:
#  client:
#    config:
#      SapService:
#        readTimeout: 5000
#        connectTimeout: 5000
